"""add table transaction

Revision ID: 36c1f650929e
Revises: 6d7fb11ada22
Create Date: 2023-12-12 04:52:57.059089

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "36c1f650929e"
down_revision: Union[str, None] = "6d7fb11ada22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quote_id", sa.String(length=120), nullable=False),
        sa.Column("transfer_id", sa.Integer(), nullable=False),
        sa.Column("target_account_id", sa.String(length=200), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("complaint_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["complaint_id"],
            ["complaint.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transaction")
    # ### end Alembic commands ###
