"""add complaint table

Revision ID: fe1cf831d6c4
Revises: 6c5b17ed4a58
Create Date: 2023-12-10 22:57:25.435949

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fe1cf831d6c4"
down_revision: Union[str, None] = "6c5b17ed4a58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "complaint",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("photo_url", sa.String(length=256), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "rejected", name="state"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("complainer_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["complainer_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("complaint")
    # ### end Alembic commands ###
